services:
  - type: web
    name: bitget-trader
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BITGET_API_KEY
        sync: false
      - key: BITGET_API_SECRET
        sync: false
      - key: BITGET_PASSPHRASE
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
